/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['router/business.js']) {
  _$jscoverage['router/business.js'] = [];
  _$jscoverage['router/business.js'][1] = 0;
  _$jscoverage['router/business.js'][3] = 0;
  _$jscoverage['router/business.js'][8] = 0;
  _$jscoverage['router/business.js'][13] = 0;
  _$jscoverage['router/business.js'][18] = 0;
  _$jscoverage['router/business.js'][23] = 0;
}
_$jscoverage['router/business.js'][1]++;
var routes = [];
_$jscoverage['router/business.js'][3]++;
routes.push({path: "/meetings", handler: "getMeetings"});
_$jscoverage['router/business.js'][8]++;
routes.push({path: "/meetings/:idMeeting", handler: ["loadMeeting", "getMeeting"]});
_$jscoverage['router/business.js'][13]++;
routes.push({path: "/meetings/:idMeeting/interventions", handler: ["loadMeeting", "getMeetingInterventions"]});
_$jscoverage['router/business.js'][18]++;
routes.push({path: "/meetings/:idMeeting/interventions/:idInt", handler: ["loadMeeting", "getMeetingIntervention"]});
_$jscoverage['router/business.js'][23]++;
module.exports = routes;
_$jscoverage['router/business.js'].source = ["var routes = []","","routes.push({","  path: '/meetings',","  handler: 'getMeetings'","})","","routes.push({","  path: '/meetings/:idMeeting',","  handler: ['loadMeeting', 'getMeeting']","})","","routes.push({","  path: '/meetings/:idMeeting/interventions',","  handler: ['loadMeeting', 'getMeetingInterventions']","})","","routes.push({","  path: '/meetings/:idMeeting/interventions/:idInt',","  handler: ['loadMeeting', 'getMeetingIntervention']","})","","module.exports = routes"];
