/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['router/deputies.js']) {
  _$jscoverage['router/deputies.js'] = [];
  _$jscoverage['router/deputies.js'][1] = 0;
  _$jscoverage['router/deputies.js'][3] = 0;
  _$jscoverage['router/deputies.js'][8] = 0;
  _$jscoverage['router/deputies.js'][13] = 0;
  _$jscoverage['router/deputies.js'][18] = 0;
  _$jscoverage['router/deputies.js'][23] = 0;
}
_$jscoverage['router/deputies.js'][1]++;
var routes = [];
_$jscoverage['router/deputies.js'][3]++;
routes.push({path: "/deputies", handler: "getDeputies"});
_$jscoverage['router/deputies.js'][8]++;
routes.push({path: "/deputies/:idDep", handler: ["loadDeputy", "getDeputy"]});
_$jscoverage['router/deputies.js'][13]++;
routes.push({path: "/deputies/:idDep/interventions", handler: ["loadDeputy", "getDeputyInterventions"]});
_$jscoverage['router/deputies.js'][18]++;
routes.push({path: "/deputies/:idDep/interventions/:idInt", handler: ["loadDeputy", "getDeputyIntervention"]});
_$jscoverage['router/deputies.js'][23]++;
module.exports = routes;
_$jscoverage['router/deputies.js'].source = ["var routes = []","","routes.push({","  path: '/deputies',","  handler: 'getDeputies'","})","","routes.push({","  path: '/deputies/:idDep',","  handler: ['loadDeputy', 'getDeputy']","})","","routes.push({","  path: '/deputies/:idDep/interventions',","  handler: ['loadDeputy', 'getDeputyInterventions']","})","","routes.push({","  path: '/deputies/:idDep/interventions/:idInt',","  handler: ['loadDeputy', 'getDeputyIntervention']","})","","module.exports = routes"];
