/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['router/interventions.js']) {
  _$jscoverage['router/interventions.js'] = [];
  _$jscoverage['router/interventions.js'][1] = 0;
  _$jscoverage['router/interventions.js'][3] = 0;
  _$jscoverage['router/interventions.js'][8] = 0;
  _$jscoverage['router/interventions.js'][13] = 0;
}
_$jscoverage['router/interventions.js'][1]++;
var routes = [];
_$jscoverage['router/interventions.js'][3]++;
routes.push({path: "/interventions", handler: "getInterventions"});
_$jscoverage['router/interventions.js'][8]++;
routes.push({path: "/interventions/:idInt", handler: ["loadIntervention", "getIntervention"]});
_$jscoverage['router/interventions.js'][13]++;
module.exports = routes;
_$jscoverage['router/interventions.js'].source = ["var routes = []","","routes.push({","  path: '/interventions',","  handler: 'getInterventions'","})","","routes.push({","  path: '/interventions/:idInt',","  handler: ['loadIntervention', 'getIntervention']","})","","module.exports = routes"];
