/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['db/connect.js']) {
  _$jscoverage['db/connect.js'] = [];
  _$jscoverage['db/connect.js'][1] = 0;
  _$jscoverage['db/connect.js'][14] = 0;
  _$jscoverage['db/connect.js'][15] = 0;
  _$jscoverage['db/connect.js'][19] = 0;
  _$jscoverage['db/connect.js'][20] = 0;
  _$jscoverage['db/connect.js'][21] = 0;
  _$jscoverage['db/connect.js'][22] = 0;
  _$jscoverage['db/connect.js'][23] = 0;
  _$jscoverage['db/connect.js'][24] = 0;
  _$jscoverage['db/connect.js'][25] = 0;
  _$jscoverage['db/connect.js'][29] = 0;
  _$jscoverage['db/connect.js'][38] = 0;
  _$jscoverage['db/connect.js'][39] = 0;
  _$jscoverage['db/connect.js'][40] = 0;
  _$jscoverage['db/connect.js'][41] = 0;
}
_$jscoverage['db/connect.js'][1]++;
var mongodb = require("mongodb"), noevil = require("see-no-evil"), mongoserver = new mongodb.Server(process.env.MONGO_HOST, parseInt(process.env.MONGO_PORT, 10), {auto_reconnect: true}), db_connector = new mongodb.Db(process.env.MONGO_DB, mongoserver), db;
_$jscoverage['db/connect.js'][14]++;
module.exports.ensureConnected = (function (cb) {
  _$jscoverage['db/connect.js'][15]++;
  var wrap = noevil({error: cb});
  _$jscoverage['db/connect.js'][19]++;
  if (! db) {
    _$jscoverage['db/connect.js'][20]++;
    db_connector.open(wrap((function (nul, theDb) {
  _$jscoverage['db/connect.js'][21]++;
  db = theDb;
  _$jscoverage['db/connect.js'][22]++;
  console.log("connected, authenticating...");
  _$jscoverage['db/connect.js'][23]++;
  db.authenticate(process.env.MONGO_USER_R, process.env.MONGO_PWD_R, wrap((function (nul, ok) {
  _$jscoverage['db/connect.js'][24]++;
  console.log("ok? " + ok);
  _$jscoverage['db/connect.js'][25]++;
  cb(null, db);
})));
})));
  }
  else {
    _$jscoverage['db/connect.js'][29]++;
    cb(null, db);
  }
});
_$jscoverage['db/connect.js'][38]++;
module.exports.end = (function () {
  _$jscoverage['db/connect.js'][39]++;
  if (db) {
    _$jscoverage['db/connect.js'][40]++;
    console.log("closing db...");
    _$jscoverage['db/connect.js'][41]++;
    db.close();
  }
});
_$jscoverage['db/connect.js'].source = ["var mongodb = require(\"mongodb\"),","  noevil = require('see-no-evil'),","  mongoserver = new mongodb.Server(process.env.MONGO_HOST,","    parseInt(process.env.MONGO_PORT, 10),","    {auto_reconnect: true}),","  db_connector = new mongodb.Db(process.env.MONGO_DB, mongoserver),","  db","","/*","** ensureConnected(cb)","**","** Makes sure there is a connection to the database, and calls the callback with the connection.","*/","module.exports.ensureConnected = function(cb) {","  var wrap = noevil({","    error: cb","  })","","  if (!db) {","    db_connector.open(wrap(function(nul, theDb) {","      db = theDb","      console.log('connected, authenticating...')","      db.authenticate(process.env.MONGO_USER_R, process.env.MONGO_PWD_R, wrap(function(nul, ok) {","        console.log('ok? ' + ok)","        cb(null, db)","      }))","    }))","  } else {","    cb(null, db)","  }","}","","/*","** end()","**","** Closes the connection to the database.","*/","module.exports.end = function() {","  if (db) {","    console.log('closing db...')","    db.close()","  }","}"];
