/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['db/index.js']) {
  _$jscoverage['db/index.js'] = [];
  _$jscoverage['db/index.js'][1] = 0;
  _$jscoverage['db/index.js'][2] = 0;
  _$jscoverage['db/index.js'][3] = 0;
}
_$jscoverage['db/index.js'][1]++;
module.exports.deputies = require("./deputies");
_$jscoverage['db/index.js'][2]++;
module.exports.interventions = require("./interventions");
_$jscoverage['db/index.js'][3]++;
module.exports.meetings = require("./meetings");
_$jscoverage['db/index.js'].source = ["module.exports.deputies = require('./deputies')","module.exports.interventions = require('./interventions')","module.exports.meetings = require('./meetings')"];
