/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['db/interventions.js']) {
  _$jscoverage['db/interventions.js'] = [];
  _$jscoverage['db/interventions.js'][1] = 0;
  _$jscoverage['db/interventions.js'][9] = 0;
  _$jscoverage['db/interventions.js'][10] = 0;
  _$jscoverage['db/interventions.js'][14] = 0;
  _$jscoverage['db/interventions.js'][15] = 0;
  _$jscoverage['db/interventions.js'][16] = 0;
  _$jscoverage['db/interventions.js'][21] = 0;
  _$jscoverage['db/interventions.js'][22] = 0;
  _$jscoverage['db/interventions.js'][26] = 0;
  _$jscoverage['db/interventions.js'][27] = 0;
  _$jscoverage['db/interventions.js'][28] = 0;
}
_$jscoverage['db/interventions.js'][1]++;
var connect = require("./connect"), noevil = require("see-no-evil"), util = require("../util"), CriteriaSpec = {meeting: {mapTo: "meetingId"}, deputy: {mapTo: "deputyId"}};
_$jscoverage['db/interventions.js'][9]++;
module.exports.get = (function (intId, cb) {
  _$jscoverage['db/interventions.js'][10]++;
  var wrap = noevil({error: cb});
  _$jscoverage['db/interventions.js'][14]++;
  connect.ensureConnected(wrap((function (nul, db) {
  _$jscoverage['db/interventions.js'][15]++;
  db.collection("interventions", wrap((function (nul, intsColl) {
  _$jscoverage['db/interventions.js'][16]++;
  intsColl.findOne({id: intId}, cb);
})));
})));
});
_$jscoverage['db/interventions.js'][21]++;
module.exports.getAll = (function (qs, cb) {
  _$jscoverage['db/interventions.js'][22]++;
  var wrap = noevil({error: cb});
  _$jscoverage['db/interventions.js'][26]++;
  connect.ensureConnected(wrap((function (nul, db) {
  _$jscoverage['db/interventions.js'][27]++;
  db.collection("interventions", wrap((function (nul, intsColl) {
  _$jscoverage['db/interventions.js'][28]++;
  intsColl.find(util.normalizeCriteria(qs, CriteriaSpec), util.buildOptionsObject(qs)).toArray(cb);
})));
})));
});
_$jscoverage['db/interventions.js'].source = ["var connect = require('./connect'),","  noevil = require('see-no-evil'),","  util = require('../util'),","  CriteriaSpec = {","    meeting: {mapTo: 'meetingId'},","    deputy: {mapTo: 'deputyId'}","  }","","module.exports.get = function(intId, cb) {","  var wrap = noevil({","    error: cb","  })","","  connect.ensureConnected(wrap(function(nul, db) {","    db.collection('interventions', wrap(function(nul, intsColl) {","      intsColl.findOne({id: intId}, cb)","    }))","  }))","}","","module.exports.getAll = function(qs, cb) {","  var wrap = noevil({","    error: cb","  })","","  connect.ensureConnected(wrap(function(nul, db) {","    db.collection('interventions', wrap(function(nul, intsColl) {","      intsColl.find(","        util.normalizeCriteria(qs, CriteriaSpec),","        util.buildOptionsObject(qs)","      ).toArray(cb)","    }))","  }))","}"];
