/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['handler/assets.js']) {
  _$jscoverage['handler/assets.js'] = [];
  _$jscoverage['handler/assets.js'][1] = 0;
  _$jscoverage['handler/assets.js'][7] = 0;
  _$jscoverage['handler/assets.js'][9] = 0;
  _$jscoverage['handler/assets.js'][10] = 0;
  _$jscoverage['handler/assets.js'][13] = 0;
  _$jscoverage['handler/assets.js'][14] = 0;
  _$jscoverage['handler/assets.js'][17] = 0;
}
_$jscoverage['handler/assets.js'][1]++;
var staticServer = require("node-static"), OneDayInMs = (86400000), path = require("path"), handler = {}, fileServer;
_$jscoverage['handler/assets.js'][7]++;
fileServer = new staticServer.Server(path.resolve(__dirname, "../../public"), {cache: OneDayInMs});
_$jscoverage['handler/assets.js'][9]++;
handler.serveIndex = (function (req, res, next) {
  _$jscoverage['handler/assets.js'][10]++;
  fileServer.serveFile("/index.html", 200, {}, req, res, next);
});
_$jscoverage['handler/assets.js'][13]++;
handler.serveFile = (function (req, res, next) {
  _$jscoverage['handler/assets.js'][14]++;
  fileServer.serve(req, res, next);
});
_$jscoverage['handler/assets.js'][17]++;
module.exports = handler;
_$jscoverage['handler/assets.js'].source = ["var staticServer = require('node-static'),","  OneDayInMs = (24 * 60 * 60 * 1000),","  path = require('path'),","  handler = {},","  fileServer","","fileServer = new staticServer.Server(path.resolve(__dirname, '../../public'), {cache: OneDayInMs})","","handler.serveIndex = function(req, res, next) {","  fileServer.serveFile('/index.html', 200, {}, req, res, next)","}","","handler.serveFile = function(req, res, next) {","  fileServer.serve(req, res, next)","}","","module.exports = handler"];
