/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['handler/index.js']) {
  _$jscoverage['handler/index.js'] = [];
  _$jscoverage['handler/index.js'][1] = 0;
  _$jscoverage['handler/index.js'][4] = 0;
  _$jscoverage['handler/index.js'][5] = 0;
  _$jscoverage['handler/index.js'][10] = 0;
  _$jscoverage['handler/index.js'][11] = 0;
  _$jscoverage['handler/index.js'][12] = 0;
  _$jscoverage['handler/index.js'][13] = 0;
  _$jscoverage['handler/index.js'][15] = 0;
}
_$jscoverage['handler/index.js'][1]++;
var util = require("../util");
_$jscoverage['handler/index.js'][4]++;
module.exports = (function (db) {
  _$jscoverage['handler/index.js'][5]++;
  var bizHandler, depHandler, assHandler, intHandler;
  _$jscoverage['handler/index.js'][10]++;
  bizHandler = require("./business")(db);
  _$jscoverage['handler/index.js'][11]++;
  depHandler = require("./deputies")(db);
  _$jscoverage['handler/index.js'][12]++;
  assHandler = require("./assets");
  _$jscoverage['handler/index.js'][13]++;
  intHandler = require("./interventions")(db);
  _$jscoverage['handler/index.js'][15]++;
  return util.extend(bizHandler, depHandler, assHandler, intHandler);
});
_$jscoverage['handler/index.js'].source = ["var util = require('../util')","","// Receive the database module as an injected dependency","module.exports = function(db) {","  var bizHandler,","    depHandler,","    assHandler,","    intHandler","","  bizHandler = require('./business')(db)","  depHandler = require('./deputies')(db)","  assHandler = require('./assets')","  intHandler = require('./interventions')(db)","","  return util.extend(bizHandler, depHandler, assHandler, intHandler)","}"];
