/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['handler/interventions.js']) {
  _$jscoverage['handler/interventions.js'] = [];
  _$jscoverage['handler/interventions.js'][1] = 0;
  _$jscoverage['handler/interventions.js'][4] = 0;
  _$jscoverage['handler/interventions.js'][5] = 0;
  _$jscoverage['handler/interventions.js'][8] = 0;
  _$jscoverage['handler/interventions.js'][9] = 0;
  _$jscoverage['handler/interventions.js'][13] = 0;
  _$jscoverage['handler/interventions.js'][14] = 0;
  _$jscoverage['handler/interventions.js'][15] = 0;
  _$jscoverage['handler/interventions.js'][16] = 0;
  _$jscoverage['handler/interventions.js'][20] = 0;
  _$jscoverage['handler/interventions.js'][21] = 0;
  _$jscoverage['handler/interventions.js'][25] = 0;
  _$jscoverage['handler/interventions.js'][26] = 0;
  _$jscoverage['handler/interventions.js'][27] = 0;
  _$jscoverage['handler/interventions.js'][28] = 0;
  _$jscoverage['handler/interventions.js'][30] = 0;
  _$jscoverage['handler/interventions.js'][35] = 0;
  _$jscoverage['handler/interventions.js'][36] = 0;
  _$jscoverage['handler/interventions.js'][37] = 0;
  _$jscoverage['handler/interventions.js'][38] = 0;
  _$jscoverage['handler/interventions.js'][41] = 0;
}
_$jscoverage['handler/interventions.js'][1]++;
var noevil = require("see-no-evil"), restify = require("restify");
_$jscoverage['handler/interventions.js'][4]++;
module.exports = (function (db) {
  _$jscoverage['handler/interventions.js'][5]++;
  var handler = {}, common = require("./common");
  _$jscoverage['handler/interventions.js'][8]++;
  handler.getInterventions = (function (req, res, next) {
  _$jscoverage['handler/interventions.js'][9]++;
  var wrap = noevil({error: next});
  _$jscoverage['handler/interventions.js'][13]++;
  db.interventions.getAll(req.query, wrap((function (nul, ints) {
  _$jscoverage['handler/interventions.js'][14]++;
  ints.forEach(common.augmentIntervention);
  _$jscoverage['handler/interventions.js'][15]++;
  res.send(ints);
  _$jscoverage['handler/interventions.js'][16]++;
  return next();
})));
});
  _$jscoverage['handler/interventions.js'][20]++;
  handler.loadIntervention = (function (req, res, next) {
  _$jscoverage['handler/interventions.js'][21]++;
  var wrap = noevil({error: next});
  _$jscoverage['handler/interventions.js'][25]++;
  db.interventions.get(req.params.idInt, wrap((function (nul, intr) {
  _$jscoverage['handler/interventions.js'][26]++;
  if (intr) {
    _$jscoverage['handler/interventions.js'][27]++;
    req.params.intr = intr;
    _$jscoverage['handler/interventions.js'][28]++;
    return next();
  }
  else {
    _$jscoverage['handler/interventions.js'][30]++;
    res.send(new restify.ResourceNotFoundError("L'identifiant d'intervention demand\u00c3\u00a9 n'existe pas."));
  }
})));
});
  _$jscoverage['handler/interventions.js'][35]++;
  handler.getIntervention = (function (req, res, next) {
  _$jscoverage['handler/interventions.js'][36]++;
  common.augmentIntervention(req.params.intr);
  _$jscoverage['handler/interventions.js'][37]++;
  res.send(req.params.intr);
  _$jscoverage['handler/interventions.js'][38]++;
  return next();
});
  _$jscoverage['handler/interventions.js'][41]++;
  return handler;
});
_$jscoverage['handler/interventions.js'].source = ["var noevil = require('see-no-evil'),","  restify = require('restify')","","module.exports = function(db) {","  var handler = {},","    common = require('./common')","","  handler.getInterventions = function(req, res, next){","    var wrap = noevil({","      error: next","    })","","    db.interventions.getAll(req.query, wrap(function(nul, ints) {","      ints.forEach(common.augmentIntervention)","      res.send(ints)","      return next()","    }))","  }","","  handler.loadIntervention = function(req, res, next) {","    var wrap = noevil({","      error: next","    })","","    db.interventions.get(req.params.idInt, wrap(function(nul, intr) {","      if (intr) {","        req.params.intr = intr","        return next()","      } else {","        res.send(new restify.ResourceNotFoundError('L\\'identifiant d\\'intervention demand&#195;&#169; n\\'existe pas.'))","      }","    }))","  }","","  handler.getIntervention = function(req, res, next) {","    common.augmentIntervention(req.params.intr)","    res.send(req.params.intr)","    return next()","  }","","  return handler","}"];
